# Generated by Django 5.1.7 on 2025-03-22 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroceryList',
            new_name='SessionList',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='grocery_list',
            new_name='session_list',
        ),
    ]
