# Generated by Django 5.1.7 on 2025-03-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_grocerylist_sessionlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchased',
        ),
    ]
